<a href="https://colab.research.google.com/github/silverjin01/2020-2-AI/blob/master/01_tf_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 버전 선택(매직 명령어)/import하기 전
%tensorflow_version 1.x  

In [ ]:
#텐서플로 1.0 버전 선택
try:
    %tensorflow_version 1.x
except Exception:
    pass

import tensorflow as tf
tf.__version__

'1.15.2'

In [ ]:
import tensorflow as tf
# constant함수를 이용해서 상수를 만듦
hello = tf.constant('Hello World!') 

#Session : 그래프를 실행시키는 객체(만들어진 그래프에 실제 값의 흐름을 수행해 결과가 나오도록 하는 객체)
sess = tf.Session()
#출력시 나오는 b는 byte타입이다? 문자열이라고 생각해도 됨
print(sess.run(hello))
sess.close()

a = 10
b = 10
#아래와 같이 하면 안나옴 session을 만들어주야함

print(tf.add(a,b)) 
sess = tf.Session()
print(sess.run(tf.add(a,b)))
sess.close()

b'Hello World!'
Tensor("Add_5:0", shape=(), dtype=int32)
20


In [ ]:
#사용 중에 버전을 바꾸려면 '런티임 다시 시작(crtl+M)'후 바로 %tensorflow_version 2.x 혹은 %tensorflow_version 1.x
%tensorflow_version 2.x

메뉴, 런타임 | 런타임 다시 시작

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [ ]:
a = tf.constant(5)
b = tf.constant(3)
print(a+b) #텐서 내용이 출력(1.x와 다르게 2.x는 값이 보여짐)

#값, 스칼라, 데이터 타입
#데이터 타입{DT_FLOAT : tf.float32
#            DT_DOUBLE : tf.float64
#            DT_INT8 : tf.int8
#            DT_INT16 : tf.int16
#            DT_INT32 : tf.int32
#             DT_INT64 : tf.int64 }

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
c = tf.constant('Hello, World!')
print(c)
print(c.numpy()) #값만 보려면 numpy()
                 #1.x버전에서는 값만 보려면 session을 만들어야 되는데 2.x버전에는 numpy()로 바로 보여질 수 있다

tf.Tensor(b'Hello, World!', shape=(), dtype=string)
b'Hello, World!'


In [ ]:
a = tf.constant(3)
a #셀에 마지막에 있으면 print를 안해도 바로 출력이 가능

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
a.shape #정의된 a의 shape형태를 출력 || 아무것도 없다는 것을 의미하는 스칼라[]

TensorShape([])

In [ ]:
a.dtype

tf.int32

In [ ]:
a.numpy()

3

In [ ]:
b = tf.constant(3.)
b

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
b.shape

TensorShape([])

In [ ]:
b.dtype

tf.float32

In [ ]:
b.numpy()

3.0

Tensor

In [ ]:
a = tf.constant([1,2,3])
a.shape #vecotr

TensorShape([3])

In [ ]:
a = tf.constant([[1,2,3],[4,5,6]])
a.shape #matrix

TensorShape([2, 3])

In [ ]:
a = tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a.shape #3-tensor

TensorShape([2, 2, 3])

In [ ]:
a #numpy로 보여지는 형식은 배열!

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

조건 연산 tf.cond()
  

```
-tf.cond(pred, true_fn=None, false_fn=None, name=None)
  -pred를 검사해 참이면 true_fc를 반환
  -pred를 검사해 거짓이면 false_fc 반환
```


In [ ]:
x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool, lambda: tf.add(x, 1.), lambda: tf.add(x, 10.))

print(res)
print(res.numpy())

tf.Tensor(2.0, shape=(), dtype=float32)
2.0


In [ ]:
x = tf.constant(2)
y = tf.constant(5)
def f1(): return tf.multiply(x,17)
def f2(): return tf.add(y, 23)
r = tf.cond(tf.less(x,y), f1, f2)

r.numpy()

34

In [ ]:
#1차원 배열 텐서
t = tf.constant([1, 6, 3])
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 6, 3], dtype=int32)>

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([5,6,7])

print((x+y).numpy()) #중요*******

[ 6  8 10]


In [ ]:
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)
print(a.numpy())

d = a + b + c

print(d)
print(d.numpy())

[5.]
tf.Tensor([17.], shape=(1,), dtype=float32)
[17.]


텐서의 브로드캐스팅


```
# shape이 다르더라도 연산이 가능하도록
  가지고 있는 값을 이용하여 Shape을 맞춤
```



In [ ]:
x = tf.constant([[0],[10],[20],[30]])
y = tf.constant([0, 1, 2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
import numpy as np

print(np.arange(3))
print(np.ones((3,3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant((np.arange(3)))
y = tf.constant([5],dtype=tf.int64)
print((x+y).numpy())

x = tf.constant((np.ones((3,3))))
y = tf.constant(np.arange(3), dtype=tf.double)
print((x+y).numpy())

x = tf.constant(np.arange(3).reshape(3,1)) #3행 1열로(세로) 
y = tf.constant(np.arange(3))
print((x+y).numpy())

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
