<a href="https://colab.research.google.com/github/silverjin01/2020-2-AI/blob/master/02_tf_interm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

In [ ]:
#텐서플로 2.0에서 즉시 실행은 기본으로 활성화
tf.executing_eagerly()

True

In [ ]:
a = tf.constant([[1,2],[3,4]])

print(a)
print(a.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


2차원 행렬 곱셈


In [ ]:
x = [[2.]]
m = tf.matmul(x,x)
print(m)
print(m.numpy())

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)
[[4.]]


In [ ]:
# Matrix multiplications 1
matrix1 = tf.constant([[1., 2.],[3., 4.]])
matrix2 = tf.constant([[2., 0.],[1., 2.]])

gop = tf.matmul(matrix1, matrix2)
print(gop.numpy())

[[ 4.  4.]
 [10.  8.]]


In [ ]:
# Matrix multiplications 2
gop = tf.matmul(matrix2, matrix1)
print(gop.numpy())

[[ 2.  4.]
 [ 7. 10.]]


In [ ]:
x = tf.constant([[10],[10],[20],[30]])
y = tf.constant([0, 1, 2])

print((x+y).numpy())

[[10 11 12]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
import numpy as np

print(np.arange(3))
print(np.ones((3,3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [ ]:
#브로드캐스팅 지원
a = tf.constant([[1,2],[3,4]])
b = tf.add(a,1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
x = tf.constant([[0],[10],[20],[30]])
y = tf.constant([0, 1, 2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
import numpy as np

print(np.arange(3))
print(np.ones((3, 3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5],dtype=tf.int64)
print(x)
print(y)
print(x+y)

[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print((x+y).numpy())

x = tf.constant((np.ones((3,3))))
y = tf.constant(np.arange(3), dtype=tf.double)
print((x+y).numpy())

x = tf.constant(np.arange(3).reshape(3, 1))
y = tf.constant(np.arange(3))
print((x+y).numpy())

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


행렬, 원소와의 곱

In [ ]:
# 연산자 오버로딩 지원
print(a)
# 텐서로부터 numpy 값 얻기 : 
print(a.numpy())
print(b)
print(b.numpy())
print(a * b)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
[[2 3]
 [4 5]]
tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [ ]:
#numpy값 사용
import numpy as np

c = np.multiply(a,b)
print(c)

[[ 2  6]
 [12 20]]


텐서플로 연산

```
tf.add() : 더하기
tf.multiply() : 곱셈
tf.pow() : 제곱
tf.reduce_mean() : 평균 구하기
tf.reduce_sum() : 합 구하기
```



In [ ]:
a = 2
b = 3
c = tf.add(a,b)
print(c.numpy())

5


In [ ]:
x = 2
y = 3
add_op = tf.add(x, y)
mul_op = tf.multiply(x, y)
pow_op = tf.pow(add_op, mul_op)

print(pow_op.numpy())

15625


In [ ]:
a = tf.constant(2.)
b = tf.constant(3.)
c = tf.constant(5.)

# Some more operations
mean = tf.reduce_mean([a,b,c]) #list형태로 
sum = tf.reduce_sum([a,b,c])

print("mean = ",mean.numpy())
print("sum = ",sum.numpy())

mean =  3.3333333
sum =  10.0


rank

```
행렬의 차수 반환
```



In [ ]:
my_image = tf.zeros([2,5,5,3])
my_image.shape #원소수는 2*5*5*3 || 4차원

TensorShape([2, 5, 5, 3])

In [ ]:
tf.rank(my_image)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
tf.rank(my_image).numpy()

4

shape, reshape



In [ ]:
rank_three_tensor = tf.ones([3,2,5])
rank_three_tensor.shape

TensorShape([3, 2, 5])

In [ ]:
rank_three_tensor.numpy()

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)

In [ ]:
#기존 내용을 6x10 행렬로 형태 변경
matrix = tf.reshape(rank_three_tensor, [6,10])
matrix

InvalidArgumentError: ignored

In [ ]:
#기존 내용을 3x20 행렬로 형태 변경
#-1은 차원 크기를 계산하여 자동으로 결정하라는 의미
matrixB = tf.reshape(matrix,[3,-1])
martixB

NameError: ignored

In [ ]:
#기존 내용을 4x3x5텐서로 형태 변경
martixAlt = tf.reshape(matrixB, [4,3,-1])
matrixAlt

NameError: ignored

In [ ]:
#형태가 변경된 텐서의 원소 개수는 원래 텐서이 원소 개수와 같습니다.
#그러므로 다음은 우너소 개수를 유지하면서
#마지막 차원에 사용 가능한 수가 없기 때문에 에러를 발행합니다.
yet_another = tf.reshape(matrixAlt, [13, 2, -1]) #에러 발생

tf.cast 자료형 변환

In [ ]:
#정수형 텐서를 실수형으로 변환
float_tensor = tf.cast(tf.constant([1,2,3]), dtype=tf.float32)
float_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
float_tensor.dtype

tf.float32

변수 Variable

In [ ]:
v = tf.Variable(0,0)
v

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>

In [ ]:
w = v + 10
w

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
w.numpy()

10

In [ ]:
v = tf.Variable(2.0)
v.assign_add(5) #값을 변수에 할당
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=7.0>

In [ ]:
v.read_value() #현재 변수값 읽기

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>



```
행렬곱셈 매우 중요
브로드캐스팅은 더더 매우 중요
shape reshape도 매우 중요(reshape에서 -1을 사용할 줄 알아야함)
```

